# Generated by Django 2.2.2 on 2019-06-20 03:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neutral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter neutral initial.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this Inquiry', primary_key=True, serialize=False)),
                ('inquirer', models.CharField(max_length=200)),
                ('date_inquiry', models.DateField(auto_now=True)),
                ('follow1', models.DateField(blank=True, null=True)),
                ('follow2', models.DateField(blank=True, null=True)),
                ('confirmed', models.DateField(blank=True, null=True)),
                ('notice_sent', models.DateField(blank=True, null=True)),
                ('closed', models.DateField()),
                ('note', models.TextField(help_text='Enter your note for this case.', max_length=1000)),
                ('neutral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adr.Neutral')),
            ],
            options={
                'ordering': ['date_inquiry'],
            },
        ),
    ]
