# Generated by Django 2.2.2 on 2019-06-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0002_auto_20190619_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='date_inquiry',
            field=models.DateTimeField(),
        ),
    ]
